### ISSUE TITLE
suoriutuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10100]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[suoriutuminen](http://www.yso.fi/onto/yso/p10270)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennettava tai poistettava

**Perustelut ehdotukselle**

Tällä hetkellä suoriutuminen YK selviytyminen -väärin ruotsin osalta, ja jos merkitys todella on enemmänkin "selviytyminen" kuin suorittaminen niin vastinetta ei varmaan saada, varsinkin kun selviytyminen on jo erillisenä terminä (klara sig).

Kielitoimiston sanakirja: suoriutua: "selviytyä, selvitä" - eli päällekkäinen selviytymisen kanssa.

Ruotsiksi tarvittaisiin kyllä joku termi suorittamiselle/suorituksille, eli presterande/prestation, mutta se ei näköjään voi olla sama kuin "suoriutuminen"? Tosin Melindassa suoriutuminen=presterande on kyllä käytetty todella paljon suorittamisesta/suorituksista, mutta onko syy englanninkieliset ja ruotsinkieliset vastineet? (Näitä viitteitä ei voi ainakaan kuvailla muillaYSO-termeillä esim. suorituskyky tai suoritteet=prestationer (produkt))

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Maria: Ks. myös https://vanha.karelia.fi/blogit/viittavaillevalmiinatyoelamaan/2019/04/05/suorittaminen-vai-suoriutuminen/ Eli merkityserot suoriutuminen selviytymisenä vs. suorittaminen "aktiivisenä tekemisenä"?

**Comment by mirmaid** [comment]
suoriutuminen (selviytyminen) KÄ selviytyminen
suoriutuminen (menestyminen) KÄ menestyminen

**Comment by mariaforsen** [comment]
Kyllä, siinä on merkitysero ja suoriutuminen selviytymisenä on ruotsiksi lähinnä "klara sig", ja tuo aktiivinen tekeminen on presterande. 

Mitä tulee rahastoihin ruotsiksi käytetään tosiaan fonders prestation, fondprestation, tämä taitaa englanniksi olla "fund perfomance"? "Fund performance is usually expressed as a percentage return over a number of different time periods, such as one month, three months, six months, one year, three years, five years, ten years and since fund inception. " Ei taida olla ihan niin yksinkertainen asia kuin voitot tms. Löytyy näköjään eri tapoja mitata rahaston tai yrityksen prestation/eng. performance, tähän liittyy käsite prestationsmått, joka on motin taloussanaston mukaan "suoritusmitta". 

Ylipäätään näyttää siltä että puhutaan englanniksi paljon "performance"ista (economic performance jne). Tämä on ruotsiksi prestation, mutta onko se suomeksi jotain muutakin kuin suoritus/suorituskyky? Ks. esim. https://lutpub.lut.fi/bitstream/handle/10024/93314/Suorituskyvyn%20mittaaminen%20mets%C3%A4koneyrityksiss%C3%A4.pdf?sequence=2 Siinä kerrotaan mm. näin: "Laitinen (1998, s. 279) määrittelee yrityksen suorituskyvyn sen kyvyksi
saada aikaan tuotoksia suhteessa asetettuihin tavoitteisiin. Yrityksen perimmäiseksi tavoitteeksi on usein nähty tuottaa omistajilleen taloudellista
hyötyä. Tästä on seurannut, että yrityksen suorituskykykin on ymmärretty
pitkään vain yrityksen talousprosessin suorituskyvyksi. Viime vuosikymmeninä näkökulma on laajentunut ja nykyään yrityksen toiminnan muut
kuin taloudelliset ulottuvuudet ovat nousseet yhä merkittävämpään rooliin
yrityksen suorituskykyä arvioitaessa (Rantanen 2001, s. 4)." 

Näyttää siltä että meillä voisi olla taloudellinen käsite erikseen jossain muodossa? Termi suorituskyky on vain ryhmissä 78 Työelämä. Työsuojelu. Työterveys
, 97 Liikunta. Urheilu

**Comment by mirmaid** [comment]
Suomeksi _suoriutuminen_ ei tosiaan talous-yhteydessä toimi, eikä myöskään _suoritus_ näytä olevan käytössä. Mahdollisesti tosiaan _tulos_ tai _tuottavuus_ ja ainakin _suorituskyky_ on tosiaan selvästi käytössä. Fund performance -käsitteestä käytetty taas _rahaston tuotot_, https://aaltodoc.aalto.fi/handle/123456789/107660.

**Comment by mirmaid** [comment]
Melindassa siis edelleen toista tuhatta viitettä, joista varmaan monissa soveltuu vielä menestyminen, selviytyminen, tai jokin muu termi (esim. opintomenestys). Joukko on kuitenkin niin sekalainen, että viitteet on käytävä läpi yksitellen ja tämänkokoisella setillä se vie paljon aikaa.

**Comment by mariaforsen** [comment]
Suorituskyky talouskäsitteenä toimisi myös ruotsin osalta, silloin voisi ohjausterminä olla "prestation (ekonomi)". Siihen liittyvät viitteet saisi sillä siivottua.

**Comment by mirmaid** [comment]
^ Eli sitten pitäisi ilmeisesti palata _suorituskyky_-käsitteen jakamiseen? Ja _suoriutuminen_ pyrittäisiin poistamaan kokonaan?

**Comment by fantsby-m** [comment]
_Suorituskyky_ -termiä tarvittaisiin myös mm. kun puhutaan koneiden tai laitteiden suorituskyvystä (esim. väitös "Effect of Manufacturing Processes on Electrical Machine’s Performance"), termi ei voine olla sama kuin nykyinen, joka on ruotsiksi 
_prestationsförmåga_.

**Comment by mariaforsen** [comment]
Koneista yms. yleensä: https://svenska.se/tre/?sok=prestanda&pz=1 Mutta ruotsiksi voisi siitä myös käyttää sanastossa oleva kapacitet.
**https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_2d2541da3b8bf2081edf5cad79a6046c&list_id=1&keyword=suorituskyky&word=suorituskyky**

**Comment by mirmaid** [comment]
Hmm, eli ilmeisesti olikin niin, että suorituskykyä ei tarvitse jakaa, vai ymmärsinkö oikein? En ole lainkaan varma miten suorituskyky istuu suomeksi erilaisiin talousalan aineistoihin, mutta ainakin osaan taitaa sopia. 

Korjasin kokeiluluonteisesti n. 50 ensimmäistä viitettä suoriutuminen-settiä - laitoin nyt suorituskyky aika laillaan kaikkeen mihin se vähänkin sopi (osaan tuli menestyminen, selviytyminen tai suorituspaineet, osasta jätin pois kokonaan). Tämän viitejoukon perusteella voi poistaa suoriutuminen-käsitteen, mutta suorituskykyyn tulee aika lailla kaikenlaista yrityksistä ja rahastoista ihmisten suorituskykyyn urheilijoina, työntekijöinä yms.

**Comment by mariaforsen** [comment]
Prestanda olisi tosiaan ruotsiksi luonnollisin termi silloin kun on kyseessä koneen tai muun teknisen laitteen suorituskyky, toisaalta myös kapacitet esim. kun kyseessä tietokone.

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_2d2541da3b8bf2081edf5cad79a6046c&list_id=1&keyword=suorituskyky&word=suorituskyky :

prestationsförmåga -n;
(koneen tms. suoritusarvot) prestanda (mon);
(työkyky) arbetsförmåga;
(kapasiteetti) kapacitet -en -er 

Mutta kompromissina ei varmaan ole mahdotonta pitää "prestationsförmåga" yleisterminä.

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan käsite _suoriutuminen_.
