### ISSUE TITLE
Villi länsi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10397]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Villi länsi](http://www.yso.fi/onto/yso/p5919)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jos tämä erisnimisenä viittaa todelliseen paikkaan, niin tulisi siirtää YSO-paikkojen puolelle ja lisätä siltaus LCSH:n "West (U.S.)" -asiasanaan [http://id.loc.gov/authorities/subjects/sh85146140]

**Perustelut ehdotukselle**

Tällä hetkellä epäselvää, mikä on asiasanan tarkoite: todellinen vai fiktiivinen paikka?

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Ei kyllä mielestäni voi linkittää tuohon ehdotettuun, koska _Villi länsi_ ei ole mikään edelleen olemassa oleva paikka. Käsitelty paljon fiktio-merkityksessä (elokuvissa, lännensarjakuvissa jne.), mutta myös historiallisena todellisena paikkana (ja samaanhan fiktiokin perustuu). 

https://en.wikipedia.org/wiki/American_frontier
_The American frontier, also known as the Old West or the Wild West, includes the geography, history, folklore, and culture in the forward wave of American expansion in mainland North America -- The legends, historical events and folklore of the American frontier have embedded themselves into United States culture so much so that the Old West, and the Western genre of media specifically, has become one of the defining periods of American national identity._

**Comment by mariaforsen** [comment]
Myös SAOssa https://id.kb.se/find?q=vilda%20v%C3%A4stern

**Comment by YSO-kokous** [comment]
### Päätös
Kokous ei kannattanut siirtämistä yso-paikkoihin. Alue nähdään myös kulttuurisena käsitteenä.
