### ISSUE TITLE
krimintataarin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11219]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

krimintataarin kieli

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://fi.wikipedia.org/wiki/Krimintataarin_kieli)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9786176799504

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [krimintataarin kieli](http://finto.fi/yse/fi/page/Y511219)

**Comment by mariaforsen** [comment]
Sv. krimtatariska HT krimturkiska
https://id.kb.se/term/sao/Krimtatariska

**Comment by tpalonen** [comment]
Kriminturkki ja Crimean Turkish ohjaustermeiksi?

==============================
Triviatieto 1

Näköjään vähän hajontaa päätermistä, mutta krimintataari lienee suositumpi muoto. LCSH:ssa on Crimean Tatar language, samoin Wikipediassa, samoin Lexvon englannin kielessä, mutta Lexvon suomen kielessä kuitenkin krimintataari KÄYTÄ kriminturkki.
https://id.loc.gov/authorities/subjects/sh85034019.html
https://finto.fi/lexvo/fi/page/crh

Triviatieto 2

Ilmeisen vaikeasti luokiteltava kieli kielitieteellisesti. Wikipedia: "Crimean Tatar has a unique position among the Turkic languages, because its three "dialects" belong to three different (sub)groups of Turkic. This makes the classification of Crimean Tatar as a whole difficult." https://en.wikipedia.org/wiki/Crimean_Tatar_language
