### ISSUE TITLE
laskimoiden tromboembolia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11693]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

laskimoiden tromboembolia

**Ehdotettu termi ruotsiksi**

venös tromboemboli

**Ehdotettu termi englanniksi**

venous thromboembolism 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [sairaudet](http://www.yso.fi/onto/yso/p2633)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 MeSH / FinMeSH laskimoiden tromboembolia http://www.yso.fi/onto/mesh/D054556

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://hdl.handle.net/10138/349894

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [laskimoiden tromboembolia](http://finto.fi/yse/fi/page/Y511693)

**Comment by FinMeSHienPaimentaja** [comment]
Puheena olevassa väitöskirjassa

http://hdl.handle.net/10138/349894

juurikin on käytetty engl.  "venous thromboembolism", jos kohta suomenkielisessä tiivistelmässä puhutaan "laskimotukoksista" ja niiden riskistä. Miten "laskimotukokset" ja "laskimoiden tromboembolia" suhtautuvat toisiinsa?
Joka tapauksessa tarpeellisia käsitteitä ja termejä ovat nämä tukoksiin ja laskimotukoksiin liittyvät termit. 

MeSH-termeistä ja niiden hierarkiasta, ks. 

Embolism and Thrombosis

A collective term for pathological conditions which are caused by the formation of a blood clot (THROMBUS) in a blood vessel, or by blocking of a blood vessel with an EMBOLUS, undissolved materials in the blood stream.

https://meshb.nlm.nih.gov/record/ui?ui=D016769


Thromboembolism

Obstruction of a blood vessel (embolism) by a blood clot (THROMBUS) in the blood stream.

https://meshb.nlm.nih.gov/record/ui?ui=D013923


Thrombosis

Formation and development of a thrombus or blood clot in the blood vessel.

https://meshb.nlm.nih.gov/record/ui?ui=D013927


Mitä nimenomaan laskimoihin tulee, MeSH:eissä alla olevat laskimotukoksia verihyytymän takia tarkoittavat termit ovat mielestäni merkitykseltään lähestulkoon samoja, itselleni ainakin hankala hahmottaa etenkin käytännön sisällönkuvailussa alla olevien laskimotukosten eroja - ehkä "Venous Thromboembolism"-termissä korostuu se tukkeutuminen...mutta käytännössä rajanveto ja erottaminen on kyllä hankalaa.

Venous Thromboembolism

Obstruction of a vein or VEINS (embolism) by a blood clot (THROMBUS) in the blood stream.

https://meshb.nlm.nih.gov/record/ui?ui=D054556


Venous Thrombosis

The formation or presence of a blood clot (THROMBUS) within a vein.

https://meshb.nlm.nih.gov/record/ui?ui=D020246


Ja sitten on vielä ainakin "syvä laskimotukos", mutta MeSH:eissä taitaa olla vain yläraajoihin liittyvänä.

**Comment by mariaforsen** [comment]
Sv. venös tromboembolism HT venös tromboemboli
uppslagsverk/encyklopedi/lång/tromboembolism
https://www.medicinskordbok.se/term/tromboembolism

**Comment by mariaforsen** [comment]
Sv. venös tromboemboli /mesh, venös tromboembolism

**Comment by ilona-x** [comment]
Linkataan tähän vielä vanha **laskimotukos**-issue https://github.com/Finto-ehdotus/YSE/issues/8753 , kun sen yhteydessä näistä käytiin paljon keskustelua, ja yhdessä kommentissa on mainittu myös tämä "venous thromboembolism".

Ainakin joissain Melinda-viitteissä, missä nimekkeessä mainitaan "venous thromboembolism", on näköjään käytetty kuvailussa asiasanaa syvä laskimotromboosi:
https://melinda.kansalliskirjasto.fi/byid/006551293
https://melinda.kansalliskirjasto.fi/byid/004858797

**Comment by mirmaid** [comment]
^ Nuo asiasanat voi olla myös mun käsialaa veritulppa-muutoksen jäljiltä. Silloin korjasin aika paljon siihen tai tromboosi-käsitteeksi (tai molemmat). Korjausta tehdessä mietin moneen kertaan, pitäisikö meillä olla lisäksi keuhkoveritulppa/keuhkoembolia, mutta en sitten enää halunnut avata tätä 🙂.

Melkein tulkitsisin, että tuo MeSHin laskimoiden tromboembolia on suurin piirtein sama kuin tämä meidän syvä laskimotromboosi.

**Comment by mirmaid** [comment]
Lääketieteen termit:
tromboembolia: veritulppauma | verisuonen tukkeutuminen verenkierron mukana tulleen hyytymän (trombin) takia
embolia: embolusten esiintyminen, veritulppien esiintyminen | yhden tai useamman verenkierron mukana kulkevan emboluksen (tavallisesti verihyytymän) aiheuttama verisuon(t)en tulppautuminen
tromboosi: verihyytymän muodostuminen verisuonen sisälle; verihyytymän esiintyminen verisuonen sisällä

**Comment by mirmaid** [comment]
Tulkitsen siis niin, että lääketieteen sanastot erottelevat toisistaan tulpan muodostumisen prosessina (tromboosi) ja tilan jossa tulppa tai tulppia on muodostunut (embolia), verenkierron mukana kulkevan tulpan (embolus) ja paikallaan olevan tulpan (trombi). Mutta kuten edelläkin todetaan niin näiden erottaminen aineistojen kuvailussa on yleensä kyllä vaikeaa ja usein myös sikäli turhaa, että aineistot käsittelevät isompaa kokonaisuutta.

Yksi mahdollisuus olisi ottaa vielä embolia, lisätä sille ja tromboosille Lääketieteen termien määritelmät ja ohjata esim. laskimoiden tromboembolia KÄ syvä laskimotromboosi, embolia? Ja ehkä tromboemboliä KÄ embolia, tromboosi?

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen sanastosta löytyy tähän liittyen:

[embolia](https://www.terveyskirjasto.fi/ltt00670/embolia?q=embolia%20ja%20tromboosi)
[tromboosi](https://www.terveyskirjasto.fi/ltt03525/tromboosi?q=embolia%20ja%20tromboosi)
[embolisaatio](https://www.terveyskirjasto.fi/ltt00671/embolisaatio?q=embolia%20ja%20tromboosi)
[sepelvaltimotukos](https://www.terveyskirjasto.fi/ltt03082/sepelvaltimotukos?q=embolia%20ja%20tromboosi)
[keuhkoembolia](https://www.terveyskirjasto.fi/ltt01571/keuhkoembolia?q=embolia%20ja%20tromboosi)
[laskimotukos](https://www.terveyskirjasto.fi/ltt01879/laskimotukos?q=embolia%20ja%20tromboosi)
[keuhkoveritulppa](https://www.terveyskirjasto.fi/ltt01588/keuhkoveritulppa?q=embolia%20ja%20tromboosi)
[tromboembolia](https://www.terveyskirjasto.fi/ltt03520/tromboembolia?q=embolia%20ja%20tromboosi)
[syvä laskimotukos](https://www.terveyskirjasto.fi/ltt03381/syva-laskimotukos?q=embolia%20ja%20tromboosi)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään Mirjan viimeisen kommentin mukaisesti.
