### ISSUE TITLE
magneettiset myrskyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11841]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[magneettiset myrskyt](http://www.yso.fi/onto/yso/p20877)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: geomagneettiset myrskyt

**Perustelut ehdotukselle**

https://tieteentermipankki.fi/wiki/Geofysiikka:magneettinen_myrsky
https://en.wikipedia.org/wiki/Geomagnetic_storm

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Nationalencklopedin: "magnetisk storm, plötslig, större störning i det geomagnetiska fältet förorsakad av elektriska strömmar i magnetosfären" Eli taitaa tosiaan olla sama asia. 

Wikipedia: "A geomagnetic storm, also known as a magnetic storm, is a temporary disturbance of the [Earth](https://en.wikipedia.org/wiki/Earth)'s [magnetosphere](https://en.wikipedia.org/wiki/Magnetosphere) caused by a [solar wind](https://en.wikipedia.org/wiki/Solar_wind) shock wave and/or cloud of magnetic field that interacts with the [Earth's magnetic field](https://en.wikipedia.org/wiki/Earth%27s_magnetic_field)."
