### ISSUE TITLE
PC ARC/INFO

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12360]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[PC ARC/INFO](http://www.yso.fi/onto/yso/p17966)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan

**Perustelut ehdotukselle**

Käsitettä käytetty vain kerran Melindassa, vuonna 1993.
https://melinda.kansalliskirjasto.fi/byid/000762917
Sanastossa on myös Arcinfo, joka on tämän seuraaja. Wikipedia: "ArcInfo (formerly ARC/INFO) is a full-featured geographic information system produced by Esri" https://en.wikipedia.org/wiki/ArcInfo

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
ArcInfo oli aiemmin Arc/Info, https://github.com/Finto-ehdotus/YSE/issues/11451. ArcInfo ei oikeastaan ole tämän seuraaja: _ESRI released a subset of ARC/INFO functionality as PC ARC/INFO for MS-DOS in 1987 and later a version for Windows using a dBase tables (instead of INFO) for tabular data and a 'Simple Macro Language' (SML)_.
