### ISSUE TITLE
serenatat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4573]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

serenatat 
#### Ehdotettu termi englanniksi

serenatas 
#### exactMatch

LCSH : Serenatas 
#### Tarkoitusta täsmentävä selite

"A dramatic cantata, normally celebratory or eulogistic, for two or more singers with orchestra. The name alludes to the fact that performance often took place by artificial light outdoors at night." (Grove Music Online) 
#### Perustelut ehdotukselle

Kyseinen käsite on ehdottoman tärkeä erottamaan oopperamaiset serenatat kantaateista yleensä, jotka voivat olla joko maallisia tai kirkollisia (ei ole eritelty Ysassa). Ja huomioksi: kyse aivan eri asiasta kuin Ysan "serenadit" 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Händels Weg von Rom nach London 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [serenatat](http://finto.fi/yse/fi/page/Y504573)

**Comment by TommiViitamies** [comment]
Luumu-ryhmä ehdottaa: hyväksytään.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)

**Comment by mirmaid** [comment]
LT kantaatit? RT serenadit, muuta?

**Comment by TommiViitamies** [comment]
LT kantaatit: kyllä. RT serenadit: ei kai (vai mitä sanoo Jaakko?)

**Comment by mirmaid** [comment]
Eng. wikipedia: In music, a serenade (or sometimes serenata, from the Italian word) is a musical composition, and/or performance, in someone's honor. Serenades are typically calm, light music.

In the Baroque era, and generally called a serenata (Italian "serenade"—since this form occurred most frequently in Italy and Vienna)—a serenata was a usually celebratory or eulogistic dramatic cantata for two or more singers and orchestra, performed outdoors in the evening by artificial light. Some composers of this type of serenade include Alessandro Stradella, Alessandro Scarlatti, Johann Joseph Fux, Johann Mattheson, and Antonio Caldara. Often these were large-scale works performed with minimal staging, intermediate between a cantata and an opera. The main difference between a cantata and a serenata, around 1700, was that the serenata was performed outdoors and therefore could use instruments which would be too loud in a small room—for example trumpets, horns and drums. https://en.wikipedia.org/wiki/Serenade

Tuon wikipedia-tekstin perusteella ajattelin että näillä voisi olla kuitenkin RT-suhde, jolloin termin _serenadit_ löytänyt huomaa että sanastossa on myös _serenatat_. Toisaalta tuo barokin serenatan määritelmä taas ehkä poikkeaa siitä mitä nykyään ajatellaan? Ja toisaalta voiko tuon määritelmän mukaan _serenata_ olla _kantaatin_ alakäsite?

**Comment by jtuohini** [comment]
RT serenadit: EI! Varsinkin, kun YSA-termi "serenadit" pitäisi sekin jakaa kahtia soitinmusiikkiserenadeihin (jotka kuuluvat samaan sävellyslajiryhmään kuin divertimentot, kassaatiot jne.) ja muihin. Jos halutaan, niin sanallinen huomautus täsmentämään käsitettä, mutta RT-suhteesta ei ole kyse.
