### ISSUE TITLE
entropia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4793]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[entropia](http://www.yso.fi/onto/ysa/Y95076) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotettu jakoa. 

#### Perustelut ehdotukselle   

YSOssa ryhmät 60 Sosiologia. Sosiaalipsykologia ja 07 Fysiikka, sekä huomautus: "eräs termodynamiikan ja informaatioteorian perussuure, haje". LT "fysikaaliset ilmiöt"

Ainakin kaksi merkitystä, fysikaalinen sekä "humanistinen": http://fi.wikipedia.org/wiki/Entropia Molempia kuvailluissa teoksissa. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
LCSH
Entropy BT Thermodynamics
Entropy (Information theory)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Entropy_in_thermodynamics_and_information_theory
https://en.wikipedia.org/wiki/Entropy_(disambiguation)

**Comment by mariaforsen** [comment]
SAO: entropi (jakamattomana, sama "perusmerkitys" vaikkakin sovellettu eri alueilla?) 

Ks. TEPA, mm. "Systeemin termodynaamisen epäjärjestyksen mitta, jota käytetään lämpöfysiikassa, informaatioteoriassa jne. Entropia kasvaa järjestyksen vähetessä." Myös: "The lower the entropy in a system, the more order there is and the more energy is available. In environmental economics the concept of entropy of a system is relevant via the Second Law of Thermodynamics (the entropy law), which states that the entropy of a system must either increase or remain unchanged. This has been used by the economist Georgescu-Rogen as the ultimate basis for economic scarcity and to argue that materials should be conserved as far as possible since their complete recycling is impossible and henceforth results in economic scarcity."

Eli voitaisiinko tulkita niin että fundamentaalisimmalla tasolla on "merkitys" sama? Muuten täytynee jakaa aika moneen "sovellusalaan" (vrt. Melinda)? Wikipedia: "Entropibegreppet används dessutom inom statistik, informationsteori, psykologi, och teorier om sinnet."
