### ISSUE TITLE
regeneratiivinen lääketiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4879]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

regeneratiivinen lääketiede 

#### Ehdotettu termi ruotsiksi   

Regenerativ medicin 

#### Ehdotettu termi englanniksi   

Regenerative Medicine 

#### exactMatch   

MeSH / FinMeSH : Regeneratiivinen lääketiede 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Heinonen, Tuomo, Innovations in Regenerative Medicine: Science fiction or a potential new industry?  http://urn.fi/URN:ISBN:978-952-03-0286-3 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

On FinMeSHissä 

**Ehdottajan nimi:** Mervi Salomaa-Rauhala 
**Ehdottajan organisaatio:** TaYK 
**Ehdottajan sähköpostiosoite:** mervi.salomaa-rauhala@uta.fi **Termiehdotus Fintossa:** [regeneratiivinen lääketiede](http://finto.fi/yse/fi/page/Y504879)

**Comment by mirmaid** [comment]
Lääketieteen termit: lääketieteen alue, joka pyrkii kehittämään keinoja korvata vaurioituneita tai puuttuvia soluja, kudoksia ja elimiä uudiskasvulla (esim. vastaavien kudosten solujen tai kantasolujen siirtoja käyttämällä)

Kudosteknologia: kudosten keinotekoinen valmistaminen tai muuntelu →kudosviljelyllä tai kantasoluista; vrt. soluterapia (1); ks. myös regeneratiivinen lääketiede, uudiskudossiirre (→ siirre)

Soluterapia: elävien solujen (esim. kantasolujen tai viljeltyjen solujen) siirto sairaan kudoksen elvyttämiseksi tai korvaamiseksi; vrt. kudosteknologia, siirto; ks. myös soluviljely, regeneratiivinen lääketiede

YSAssa on _kudosteknologia_, _kudoksensiirto_, _solusiirto_ ja _kantasolujen siirto_.

LCSH: Regenerative Medicine

MeSHissä ei ole termejä _kudosteknologia_ ja _soluterapia_.

Melindassa kolme kertaa.

**Comment by mirmaid** [comment]
Regenerative medicine is a broad field that includes tissue engineering but also incorporates research on self-healing – where the body uses its own systems, sometimes with help foreign biological material to recreate cells and rebuild tissues and organs.  The terms “tissue engineering” and “regenerative medicine” have become largely interchangeable, as the field hopes to focus on cures instead of treatments for complex, often chronic, diseases. https://www.nibib.nih.gov/science-education/science-topics/tissue-engineering-and-regenerative-medicine

https://en.wikipedia.org/wiki/Regenerative_medicine

https://www.quora.com/Stem-Cells-What-is-the-difference-between-regenerative-medicine-and-tissue-engineering

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
regenerativ medicin
