### ISSUE TITLE
a cappella -musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6873]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[a cappella -musiikki](http://www.yso.fi/onto/ysa/Y214758) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Miksi tämä on nykyisen suomenkielisen huomatuksen mukaan rajoitettu pelkästään kuoro- tai yhtyelauluun? Myös soololaulu voi olla a cappella. Ruotsiksi huomautus on: Sång utan instrumentalt ackompanjemang. 

#### Perustelut ehdotukselle   

Ks. sanakirjat, Nationalencyklopedin etc. Myös https://sv.wikipedia.org/wiki/A_cappella

**Comment by jtuohini** [comment]
Groven musiikkitietosanakirjan mukaan "A cappella (alla cappella) (It.: 'in the style of the church (chapel)'). Normally, choral music sung without instrumental accompaniment. Originally (c1600) the term was used to distinguish works composed in the older polyphonic style of the Renaissance from those written in the newer concertato style of the early Baroque. During the 19th century the Roman Catholic Church idealized 16th-century polyphony and the works of Palestrina in particular. Noting that no instrumental parts were included in the sources containing this music, and unaware that instruments were often used during the Renaissance to double or substitute for vocal parts, musicians came to believe that a cappella referred to unaccompanied choral singing [- -]. Since that time, the term has become synonymous with 'unaccompanied singing', both religious and secular. [- -]" [https://doi.org/10.1093/gmo/9781561592630.article.00091]

**Comment by jtuohini** [comment]
Ja vielä täydennykseksi: tuskin kenellekään tulee mieleen nimittää esimerkiksi kansanlaulajan yksinään esittämiä kansanlauluja a cappella -musiikiksi. Säestyksetön yhtyelaulu populaamusiikin puolella sekä yhtye- ja kuorolaulu länsimaisen taidemusiikin puolella taitavat olla käytetyimmät alat kuvailun kannalta?

**Comment by MUUSA-kokous** [comment]
Kannatamme nykyisen määritelmän säilyttämistä. Pidämme Grovea tässä pääauktoriteettinä.

**Comment by JohPa** [comment]
Tämä tarvitaan myös slm-sanastoon!

**Comment by YSA-kokous** [comment]
Ei muutoksia / YSA
