### ISSUE TITLE
katalaanin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7527]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[katalaanin kieli](http://www.yso.fi/onto/ysa/Y102276) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT valencian kieli (vai erillisenä terminä) ? 

#### Perustelut ehdotukselle   

Käytetty Melindassa. Ks. myös https://fi.wikipedia.org/wiki/Valencian_kieli

**Comment by jtuohini** [comment]
LCSH-vastine valencian kielelle: [Catalan language--Dialects--Spain--Valencia (Region)](http://id.loc.gov/authorities/subjects/sh2009118501).

**Comment by mirmaid** [comment]
There is a political controversy within the Valencian Community regarding its status as a glottonym or as a language on its own, since official reports show that slightly more than half of the people in the Valencian Community consider it as a separate language, different from Catalan, although the same studies show that this percentage decreases dramatically among younger generations and people with higher studies. https://en.wikipedia.org/wiki/Valencian

Ei ISO-kielikoodia.

**Comment by YSA-kokous** [comment]
Hyväksytään valencian kieli ohjaustermiksi.
Käytetään ISOa tässä auktoriteettinä (ei ISO-koodia). Tästä syystä ei erilliseksi käsitteeksi.
