### ISSUE TITLE
aasialainen kulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7816]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aasialainen kulttuuri 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 

#### Perustelut ehdotukselle   

Muita x-kulttuuritermejä on otettu. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kivi, kukka ja kuu. Teoksessa tutkitaan aasialaisen ja länsimaisen kulttuurin eroja siitä, mitä ympäristöestetiikka/-filosofia tarkoittaa kummassakin kulttuuriympäristössä. 

**Ehdottajan organisaatio:** Kirjastopalvelu, OH **Termiehdotus Fintossa:** [aasialainen kulttuuri](http://finto.fi/yse/fi/page/Y507816)

**Comment by mariaforsen** [comment]
YSOssa ei ole kyllä muita vastaavia.

**Comment by mariaforsen** [comment]
Aivan vastaavia ei taida olla, esim. amerikkalainen/eurooppalainen kulttuuri. Onko ajateltu että tällaisissa tapauksisssa käytetää Aasia + kulttuuri?

**Comment by mariaforsen** [comment]
Sv. asiatisk kultur

**Comment by mariaforsen** [comment]
Sv. asiatisk kultur. Tosin olisiko tässä hyvä käyttää jo sanastossa oleva itämainen kulttuuri? Sanastossa ei myöskään ole vastaavia "amerikkalainen kulttuuri", "eurooppalainen kultturi" jne.

**Comment by YSO-kokous** [comment]
Ei hyväksytä ehdotusta.

**Comment by tpalonen** [comment]
Palaisin vielä tähän. Aasialainen kulttuuri on mielestäni huomattavasti neutraalimpi termi kuin itämainen kulttuuri, joka tuntuu nykymaailmassa vanhahtavalta ja orientalistiselta. Voisin vähän tehdä taustatyötä ja palata pitemmästi.

**Comment by tpalonen** [comment]
Lainaus Tiede-lehdestä 6/2013: _"Orientti tai itämaat on kulttuurinen käsite pikemmin kuin maantieteellinen, siksi se on vähän epämääräinen. Eri aikoina itämailla on tarkoitettu eri osia Aasiasta ja Pohjois-Afrikasta. Aluksi orienttiin laskettiin Lähi-itä, sitten käsite laajeni kattamaan islamilaisen Pohjois-Afrikan, Intian niemimaan, Kiinan, Japanin ja Korean. Pohjois-Aasiaa ei kuitenkaan yleensä luettu mukaan. Orientti on hyvin Eurooppa-keskeinen käsite, ja se on aina määritelty Euroopan vastakohdaksi. Termi antaa ymmärtää, että on olemassa yhtenäinen itä, joka eroaa lännestä. Mutta eiväthän Kiina, Japani ja arabimaailma muodosta yhtenäistä kokonaisuutta, jolla pitäisi olla jokin nimi. **Tutkimuksessa sanaa käytetäänkin enää ani harvoin, ja sitä pidetään vahvasti arvolatautuneena.**"_ https://www.tiede.fi/artikkeli/kysy/minka_rajan_mukaan_ita_ja_lansimaat_erotellaan

Kotuksen Eksonyymit-sanaston mukaan itämaat on historiallinen nimitys. Ks. http://kaino.kotus.fi/eksonyymit/?a=tietue&id=1450&ex=it%C3%A4maat

Kielitoimiston sanakirja, Eksonyymit-sanasto ja Wikipedia (sekä myös Tiede-lehti yllä) esittävät itämaat synonyymina sanalle orientti. Näitä vastaa esim. englannin termi orient. Käsitettä ja termiä on kritisoitu paljon Edward Saidin klassisesta Orientalismi-kirjasta (1978) lähtien. Wikipedia: _"The notion of an Orient has played a central role in constructing European culture, and “helped to define Europe (or the West) as its contrasting image, idea, personality, experience.”:1–2 The binary relationship of strong-West-and-weak-East reinforces the cultural stereotypes invented with literary, cultural, and historical texts that are more fictitious than factual; yet, which give the reader of Orientalist texts (history, travelogue, anthropology, etc.) a limited understanding of life in the Middle East, because Orientalism conflates the different societies of the Eastern world, into the homogeneous world of "the Orient.""_ 
https://en.wikipedia.org/wiki/Orientalism_(book)
_"Yhteiskuntatieteellisessä tutkimuksessa orientti nähdään lännen luomana käsitteenä. Edward Said esittää teoksessaan Orientalismi (1978), että orientti on läntisen voimien, tieteentekijöiden, filosofien ja taiteilijoiden luoma käsite. Saidin mukaan länsi on toiseuttanut idän ja tehnyt siitä hegemonisen kulttuuris-maantieteellisen alueen samalla yleistäen alueelle tiettyjä ominaispiirteitä."_ https://fi.wikipedia.org/wiki/Orientti

Vrt. Helsingin yliopistossa on oppiaineena "Aasian tutkimus", Turun yliopistossa "Itä-Aasian tutkimus". Itämään/itämaiden/itämaatutkimus-nimityksiä ei ole käytössä kotimaisissa yliopistoissa.

Suosittaisin, että käsitteen termi (http://www.yso.fi/onto/yso/p13460) muodostettaisiin neutraalimmin maanosan nimen mukaan eikä sen mukaan, missä suunnassa se on Euroopasta katsoen. Samalla voisi tarkastella myös YSOn termejä itämainen filosofia, itämaiset kielet, itämainen tanssi ja itämaiset matot.

**Comment by krinay** [comment]
Ymmärrän em. perustelut, mutta asia on monimutkainen. Esimerkiksi itämainen tanssi tai itämaiset matot voivat olla myös pohjoisafrikkalaisia. Itämainen viittaa usein (myös) arabialaiseen kulttuuriin.

YSOssa on _itämaisen kulttuurin_ lisäksi _länsimainen kulttuuri_.

**Comment by tpalonen** [comment]
Se juuri on yksi itämaa-termin ongelmista: se ei viittaa mihinkään todelliseen yhtenäiseen kulttuurialueeseen, vaan on eräänlainen eurooppalaisesta näkökulmasta "eksoottisten" kulttuurien kaatoluokka. Pohjoisafrikkalaisella ja japanilaisella kulttuurilla on yhtä paljon tai vähemmän tekemistä toistensa kanssa kuin vaikkapa pohjoisafrikkalaisella ja suomalaisella kulttuurilla.

Pohjois-Afrikkaan liittyen YSOssa on käsitteitä kuten arabialainen filosofia, arabialainen musiikki ja islamilainen taide. Nämä ovat _itämainen kulttuuri / itämainen filosofia_ -tyyppisiä käsitteitä paljon tarkempia, perustuvat yleisesti tunnistettuihin kulttuurialueisiin (tai uskontoon) ja ovat myös varsin kelvollisia pohjoisafrikkalaisen filosofian/musiikin/taiteen yhteydessä sikäli, kun kyse on arabialaisesta filosofiasta/musiikista tai islamilaisesta taiteesta. Esim. tuaregien kulttuurista puhuttaessa eivät kuitenkaan soveltuisi, koska tuaregit eivät ole arabeja. Myös islamilainen kulttuuri löytyy sanastosta. Islamilainen ja arabialainen kulttuuri eivät toki ole sama asia: maapallon maista eniten muslimeja tällä hetkellä on Indonesiassa.

**Comment by krinay** [comment]
Ilmaisin itseäni epäselvästi. Pääasiallinen tarkoitukseni oli kommentoida ehdotusta tarkastella samalla termejä _itämainen tanssi_ ja _itämaiset matot_. Ne lienevät jollakin tavalla selvempiä merkitykseltään kuin termi _itämainen kulttuuri_, ja niitä olisi aika vaikea korvata muulla termillä.

Myös _aasialainen kulttuuri_ on minusta ongelmallinen käsite. Lähi-idän ja Itä-Aasian maiden kulttuureilla ei taida olla juuri sen enempää yhteistä keskenään kuin Lähi-idän ja Euroopan maiden kulttuureilla.

**Comment by mirmaid** [comment]
Kuinka yhtenäinen sitten on käsitteenä _länsimaat_ tai _länsimainen kulttuuri_...kommentoinkin jo aikaisemmin, että mielestäni on lähes yhtä orientalistista meidän länsimaisesta näkökulmastamme päättää, ettei voida puhua itämaisesta kulttuurista (mutta voidaan puhua länsimaisesta), kuin että siitä voidaan puhua - kumpikin sisältää olettamuksen, että nimenomaan me täällä lännessä päätämme valta-asemastamme käsin, miten saa puhua. Sikäli tämä tietenkin on väistämätöntä, ettemme voi nyt kysyä, voisiko itämainen kulttuuri olla länsimaisen kulttuurin tavoin käyttökelpoinen käsite marokkolaisesta, turkkilaisesta, intialaisesta tai korealaisesta näkökulmasta, ja missä näiden rajalinja mistäkin katsoen kulkee.

**Comment by tpalonen** [comment]
Olen suoraan sanoen vähän hämmentynyt, että tämä herättää näin paljon keskustelua. En nyt aamutuimaan pysty kaivamaan enää aihetta käsittelevää kirjallisuutta enempää. Kuitenkin: länsimaat on edelleen yleiskielessä ja asiatekstissäkin hyväksytty termi. Itämaat/itämainen/orientti taas ei niinkään, kuten olen edellä esittänyt. Länsimaat-termissä toki on sama länsi/itä tai me/ne -asetelma, mutta positio ja valtasuhteet tekevät tästä aivan eri asian kuin itämaa/orientti-termeistä. Niin kutsutuissa länsimaissa asuvat ihmiset käyttävät itse länsimaat-termiä, mutta pohjoisafrikkalaiset, japanilaiset jne tuskin käyttävät alueestaan nimitystä itämaat tai orientti. Tämä on positio- ja valtakysymys: kuka saa määrittää, mitä nimityksiä mistäkin alueesta käytetään. Niin kutsutuilla länsimailla on ollut valtapositio, jonka kautta maailma on jaettu "meidän" alueeseen ja "eksoottisiin" itämaihin. 

Tämä on todettu monessa aihepiirissä viime aikoina (vrt. esim. saamelaiset) ja pätee tähänkin yhteyteen: valta-asemassa oleva ei voi itse määrittää, onko jokin vähemmistöä koskeva termi loukkaava.

**Comment by jarmosaarikko** [comment]
wikidatassa on valittu päätermiksi "_Aasian kulttuurit_" - https://www.wikidata.org/wiki/Q149806, jolle on annettu synonyymiksi  "_itämaiset kulttuurit_"
Uuden käsitteen asemesta ehdotan vain päätermin vaihtamistä seuraaviin käsitteisiin. Nykyiset päätermit ohjaustermeiksi
- http://www.yso.fi/onto/yso/p13460  Itämaiset kielet  KÄYTÄ aasialaiset kielet | asiatiska språk | Asian languages
- http://www.yso.fi/onto/yso/p18194 itämainen kulttuuri KÄYTÄ  aasialainen kulttuuri | asiatisk kultur | Asian culture  (monikko?)
- http://www.yso.fi/onto/yso/p3109 itämainen filosofia  KÄYTÄ aasialainen filosofia | asiatisk filosofi | Asian philosophy (monikko?)

**Comment by mariaforsen** [comment]
SAOssa on jonkin verran asiatisk... -termejä, mutta ei ollenkaan österländsk -alkuisia termejä. https://id.kb.se/find?q=asiatisk%2a

**Comment by AuHo22** [comment]
Lainaus: _Mutta eiväthän Kiina, Japani ja arabimaailma muodosta yhtenäistä kokonaisuutta, jolla pitäisi olla jokin nimi._ 
Meillä on tällä hetkellä käsite **orientalismi,** joka on hyödyllinen esim. taiteen virtauksia kuvatessa ja yleisemminkin tarkoittanee tiettyä historiallista Orienttiin suuntautuvaa harrastusta. Mutta kuten sanottu, niin Aasia on monimuotoinen kokonaisuus, ja tarvittaessa (?) po. kuvata sitä monikolla aasialaiset kulttuurit + Japani/japanilaisuus tms.

**Itämainen filosofia** kytketään usein jonkin oppisuunnan kanssa, olipa se kungfutselaisuus, zenbuddhalaisuus tms. ja on mielestäni aika vakiintunut käytössään, esim. Wikipedia: https://fi.wikipedia.org/wiki/It%C3%A4mainen_filosofia

->LC on näköjään korvannut vanhemman termin Philosophy, Oriental -> **Philosophy, Asian**, mutta Rameau puolestaan päinvastoin: **Philosophie orientale** KT Philosophie asiatique. Saksan kansalliskirjastolla on sitten oma hyvin hienojakoinen jaottelunsa.

_Itämaiset kielet KÄYTÄ aasialaiset kielet | asiatiska språk | Asian languages_ lienee monimutkaisin kokonaisuus:
**LC Oriental languages**. Here are entered works on the indigenous languages of Asia. **LT Asia--Languages**
**Rameau:** **Langues asiatiques** + alajako kielikunnittain **LT Langues -- Asie**
Saksan kansalliskirjastossa on euraasialaisten kielten ST:nä https://portal.dnb.de/opac/showFullRecord?currentResultId=ubRef%3D950949337%26any&currentPosition=1

**Comment by LeKorsu** [comment]
Komppaan Aulia tuosta monikkomuodosta (aasialaiset kulttuurit) ja tarvittaessa valtio(t) tarkenteena.

**Comment by mirmaid** [comment]
Monikko kuulostaa hyvältä ajatukselta.

Ehdotetuista muista tarkasteltavista _itämaiset kielet_ voisi varmaankin poistaa - käytetty Melindassa 64 kertaa, mutta termi _orientalistiikka_ kattaa varmaan pitkälle sen mitä halutaan sanoa, ja usein onkin näissä viitteissä.

Muuten en tekisi muutoksia.

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan _itämainen kulttuuri_, tilalle _aasialaiset kulttuurit_. 

Poistetaan _itämaiset kielet_.

**Comment by mariaforsen** [comment]
Sv. asiatiska kulturer
