### ISSUE TITLE
molekyylikerroskasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8036]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

molekyylikerroskasvatus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Upconverting luminescent materials for solar energy conversion 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [molekyylikerroskasvatus](http://finto.fi/yse/fi/page/Y508036)

**Comment by mirmaid** [comment]
Kerran Melindassa, 15 viitettä Googlella :-). Englanniksi tunnetumpi, https://en.wikipedia.org/wiki/Molecular_layer_deposition: _Even though MLD is a known technique in the thin film deposition sector, due to its relative youth it is not as explored as its inorganic counterpart, ALD, and a wide sector development is expected in the upcoming years._

**Comment by mariaforsen** [comment]
Sv. molekyllagerdeponering?

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
