### ISSUE TITLE
onni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9869]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[onni](http://www.yso.fi/onto/yso/p2415)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

vaihdetaan eng. päätermi muotoon "luck"  tai lisätään se ohjaustermiksi

**Perustelut ehdotukselle**

luck - termiä ei löydy sanastosta

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mariaforsen** [comment]
Onni on monimerkityksinen termi, ks. esim. https://www.kielitoimistonsanakirja.fi/#/onni?searchMode=all Jos todella vaihdettaisiin eng. termi > luck (oxford: "success or failure apparently brought by chance rather than through one's own actions") niin myös ruotsinnos pitäisi muuttaa (>tur, fi. "tuuri"). Tämä rajaa termin merkitys eri tavalla ruotsiksi ja englanniksi, verrattuna suomenkieliseen (nyt monimerkityksiseen) termiin. Termi pitäisi rajata samalla tavalla kaikilla kielillä (onko tarkenne tarpeen?).

**Comment by mirmaid** [comment]
Onko tarpeen lähteä tähän hyvin hankalaan rajaamiseen?

**Comment by krinay** [comment]
Kansanperinteen/kansanuskon(kin) tutkimuksessa käsite _onni_ on tärkeä. Siinä yhteydessä ruotsinkielinen vastine on usein _lycka_ ja englanninkielinen _fortune_ (joka voi tietenkin harmillisesti sekaantua omaisuuteen), ks. esim. 
https://melinda.kansalliskirjasto.fi/byid/000318115

LCSH: https://id.loc.gov/authorities/subjects/sh85050990.html

**Comment by mirmaid** [comment]
Itse en siis näe tässä tarvetta muutokseen. Jos ei ole tarkempaa toivetta siitä, mitä pitäisi muuttaa tai mikä ongelma korjata, jättäisin tämän entiselleen (mahd. eng. termien tarkistus kuitenkin).

**Comment by krinay** [comment]
Kannatan englanninkielisen termin muuttamista LCSH:n mallin mukaisesti:

onni – fortune KT luck
https://id.loc.gov/authorities/subjects/sh85050990.html 

onnellisuus – happiness KT gladness 
https://id.loc.gov/authorities/subjects/sh85058807.html

**Comment by YSO-kokous** [comment]
**Päätös**

Vaihdetaan englannin termi ehdotetulla tavalla.
